appName: nodetodo
namespace: hc
replicaCount: 1

image:
  repository: "trainwithshubham/node-app"
  tag: "latest"
  # pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  name: ""

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30003

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      # paths:
      #   - path: /
      #     pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 128m
    memory: 256Mi
  requests:
    cpu: 64m
    memory: 128Mi


livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80